<template>
    <section ref="home" id="HOME">
        <MatrixRain/>
        <article class="drop-anim absolute flex flex-col gap-5 justify-center content-center items-center w-[100%] h-[100%] bg-gradient-to-t from-background">
            <img class="max-w-[200px] rounded-full" src="../assets/images/portrait.png"
                 alt="Picture of Ruben Sanchez generated by DawnAI"/>
            <article class="text-center">
                <h1 class="font-extralight tracking-widest">
                    Front-End Developer and Space Enthusiast
                </h1>
                <h3 class="text-5xl xl:text-7xl font-extralight tracking-widest">
                    Ruben Sanchez
                </h3>
            </article>
            <form class="flex gap-5 flex-wrap max-w-[50vw] xl:max-w-[100vw] justify-center align-center">
                <CustomButton>
                    <span class="align-middle xl:text-base">
                        GET RESUME
                    </span>
                    <mdicon class="ml-2 align-middle" size="20" name="tray-arrow-down"/>
                </CustomButton>
                <a href="https://github.com/Ruben1729" target="_blank">
                    <mdicon class="text-indigo-500 hover:text-indigo-600 cursor-pointer duration-150" size="35"
                            name="github"/>
                </a>
                <a href="https://www.linkedin.com/in/ruben-sanchez-3a643917a/" target="_blank">
                    <mdicon class="text-indigo-500 hover:text-indigo-600 cursor-pointer duration-150" size="35"
                            name="linkedin"/>
                </a>
                <a href="mailto: ruben.e.sanchez.a@gmail.com">
                    <mdicon class="text-indigo-500 hover:text-indigo-600 cursor-pointer duration-150" size="35" name="at"/>
                </a>
            </form>
        </article>
        <CustomNavigation :active-section="currentSection" :navigation-links="['HOME', 'EXPERIENCE', 'PROJECTS', 'ABOUT ME']"/>
        <CustomButton :openInNew="false" destination="#HOME" v-if="isScrollUpVisible" class="visible xl:invisible fixed z-20 bottom-0 right-0 m-10 px-0 py-0"><mdicon size="40" name="chevron-up"/></CustomButton>
    </section>
    <section ref="experience" id="EXPERIENCE" class="px-5 lg:px-10 xl:px-0">
        <article class="grid grid-cols-2 lg:grid-cols-4 gap-5">
            <CustomHeading class="col-span-2 lg:col-span-4 justify-self-center">
                <span class="text-indigo-400">01.</span> PROFESSIONAL EXPERIENCE
            </CustomHeading>
            <p class="col-span-2 lg:col-span-4 lg:max-w-2xl text-center">
                Throughout my different internships and work experiences I've
                learnt and developed my skills in the following technologies:
            </p>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/html.svg" alt="HTML logo"/>
                <figcaption>HTML</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/css.svg" alt="CSS logo"/>
                <figcaption>CSS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/sass.svg" alt="SASS logo"/>
                <figcaption>SASS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                <figcaption>Javascript</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                <figcaption>VueJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nuxtjs.webp" alt="NuxtJS logo"/>
                <figcaption>NuxtJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nestjs.svg" alt="NestJS logo"/>
                <figcaption>NestJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/capacitor.webp" alt="Capacitor logo"/>
                <figcaption>Capacitor</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                <figcaption>MySQL</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/tailwind.webp" alt="TailwindCSS logo"/>
                <figcaption>TailwindCSS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                <figcaption>NodeJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/cpp.png" alt="C++ logo"/>
                <figcaption>C++</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/arduino.svg" alt="Arduino logo"/>
                <figcaption>Arduino</figcaption>
            </figure>
        </article>
        <div class="relative">
            <CanvasGrid class="absolute"/>
            <article id="job-descriptions"
                     class="px-5 lg:px-0 relative z-10 grid xl:grid-cols-2 py-28 gap-10 xl:gap-20 items-center w-[100vw] h-[100%] bg-gradient-to-b from-background">
                <CustomJobDescription class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                    <template v-slot:company>
                        <AnimatedLink destination="https://rlpindustries.com/" :fade="false">
                            <span class="flex justify-center items-center gap-1">
                                RLP Industries <mdicon size="20" name="open-in-new"/>
                            </span>
                        </AnimatedLink>
                    </template>
                    <template v-slot:position>
                        Full-Stack Developer
                    </template>
                    <template v-slot:date>
                        MAR 2022 - DEC 2022
                    </template>
                    <template v-slot:images>
                        <figure class="flex gap-3 flex-wrap">
                            <img class="w-7" src="../assets/images/html.svg" alt="HTML logo"/>
                            <img class="w-7" src="../assets/images/css.svg" alt="CSS logo"/>
                            <img class="w-7" src="../assets/images/sass.svg" alt="SASS logo"/>
                            <img class="w-7" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                            <img class="w-7" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                            <img class="w-7" src="../assets/images/nuxtjs.webp" alt="NuxtJS logo"/>
                            <img class="w-7" src="../assets/images/nestjs.svg" alt="NestJS logo"/>
                            <img class="w-7" src="../assets/images/capacitor.webp" alt="Capacitor logo"/>
                            <img class="w-7" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                            <img class="w-7" src="../assets/images/tailwind.webp" alt="TailwindCSS logo"/>
                            <img class="w-7" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                        </figure>
                    </template>
                    <template v-slot:content>
                        <li class="flex">
                            <mdicon class="text-indigo-400 flex" name="menu-right"/>
                            Designed and developed a web-app using Vue technologies (VueJS, NuxtJS, Capacitor).
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Built an API to interact with a web-app and a website using NodeJS and NestJS.
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Developed the main landing website for the company.
                        </li>
                    </template>
                </CustomJobDescription>
                <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                    <img class="rounded-sm" src="../assets/images/rlpindustries-website.png"
                         alt="RLP Industries Website Snippet"/>
                </figure>
                <CustomJobDescription class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                    <template v-slot:company>
                        <AnimatedLink destination="https://www.concordia.ca/" :fade="false">
                            <span class="flex justify-center items-center gap-1">
                                Concordia University <mdicon size="20" name="open-in-new"/>
                            </span>
                        </AnimatedLink>
                    </template>
                    <template v-slot:position>
                        Teaching Assistant & Lab Instructor
                    </template>
                    <template v-slot:date>
                        SEP 2021 - DEC 2022
                    </template>
                    <template v-slot:images>
                        <figure class="flex gap-3 flex-wrap">
                            <img class="w-7" src="../assets/images/cpp.png" alt="C++ logo"/>
                            <img class="w-7" src="../assets/images/arduino.svg" alt="Arduino logo"/>
                        </figure>
                    </template>
                    <template v-slot:content>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Teach the basics of cpp programming.
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Lead and instruct the laboratories.
                        </li>
                    </template>
                </CustomJobDescription>
                <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                    <img class="rounded-sm" src="../assets/images/arduino-lab-demo.png"
                         alt="Arduino Lab Demonstration"/>
                </figure>
                <CustomJobDescription class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                    <template v-slot:company>
                        <AnimatedLink destination="https://thefoodforce.com/" :fade="false">
                            <span class="flex justify-center items-center gap-1">
                                Eye-In Media <mdicon size="20" name="open-in-new"/>
                            </span>
                        </AnimatedLink>
                    </template>
                    <template v-slot:position>
                        Full-Stack Developer
                    </template>
                    <template v-slot:date>
                        MAR 2022 - DEC 2022
                    </template>
                    <template v-slot:images>
                        <figure class="flex gap-3 flex-wrap">
                            <img class="w-7" src="../assets/images/html.svg" alt="HTML logo"/>
                            <img class="w-7" src="../assets/images/css.svg" alt="CSS logo"/>
                            <img class="w-7" src="../assets/images/sass.svg" alt="SASS logo"/>
                            <img class="w-7" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                            <img class="w-7" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                            <img class="w-7" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                            <img class="w-7" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                        </figure>
                    </template>

                    <template v-slot:content>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Was chosen as a lead for an experimental project that was turned into a product.
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Designed and implemented data models as well as the employee interface to modify the
                            database.
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Built phone applications using Vue technologies (Vue Native, Vue Nativescript).
                        </li>
                        <li class="flex">
                            <mdicon class="text-indigo-400 inline" name="menu-right"/>
                            Developed an API using NodeJS to interact with the database.
                        </li>
                    </template>
                </CustomJobDescription>
                <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                    <img class="rounded-sm" src="../assets/images/foodforce-website.png"
                         alt="TheFoodForce Website Snippet"/>
                </figure>
            </article>
        </div>
    </section>
    <section ref="projects" id="PROJECTS" class="px-5 xl:px-0 bg-slate-900 border-y-[1px] border-gray-700 pb-16">
        <article class="grid grid-cols-2 lg:grid-cols-4 gap-5">
            <CustomHeading class="col-span-2 lg:col-span-4 justify-self-center">
                <span class="text-indigo-400">02.</span> PERSONAL PROJECTS
            </CustomHeading>
            <p class="col-span-2 lg:col-span-4 lg:max-w-2xl text-center">
                I spend a lot of my free time working on different programming projects.
                While the following section only showcases my top three favorite projects, you can find the rest of them
                on my
                <a href="https://github.com/Ruben1729" target="_blank"
                   class="text-indigo-300 font-semibold cursor-pointer hover:text-indigo-200 duration-150">Github</a>
                .Throughout these projects, I've used the following technologies:
            </p>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/html.svg" alt="HTML logo"/>
                <figcaption>HTML</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/css.svg" alt="CSS logo"/>
                <figcaption>CSS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/sass.svg" alt="SASS logo"/>
                <figcaption>SASS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                <figcaption>Javascript</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                <figcaption>VueJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nuxtjs.webp" alt="NuxtJS logo"/>
                <figcaption>NuxtJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nestjs.svg" alt="NestJS logo"/>
                <figcaption>NestJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/capacitor.webp" alt="Capacitor logo"/>
                <figcaption>Capacitor</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                <figcaption>MySQL</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/tailwind.webp" alt="TailwindCSS logo"/>
                <figcaption>TailwindCSS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                <figcaption>NodeJS</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/cpp.png" alt="C++ logo"/>
                <figcaption>C++</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/python.svg" alt="Python logo"/>
                <figcaption>Python</figcaption>
            </figure>
            <figure class="flex items-center gap-2">
                <img class="w-10" src="../assets/images/freertos.png" alt="FreeRTOS logo"/>
                <figcaption>FreeRTOS</figcaption>
            </figure>
        </article>
        <div class="grid xl:grid-cols-2 gap-10 xl:gap-20 items-center pt-20">
            <CustomArticle class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                <template v-slot:company>
                    Personal
                </template>
                <template v-slot:header>
                    Reach Loyalty
                </template>
                <template v-slot:images>
                    <figure class="flex gap-3 flex-wrap">
                        <img class="w-7" src="../assets/images/html.svg" alt="HTML logo"/>
                        <img class="w-7" src="../assets/images/css.svg" alt="CSS logo"/>
                        <img class="w-7" src="../assets/images/sass.svg" alt="SASS logo"/>
                        <img class="w-7" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                        <img class="w-7" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                        <img class="w-7" src="../assets/images/nuxtjs.webp" alt="NuxtJS logo"/>
                        <img class="w-7" src="../assets/images/nestjs.svg" alt="NestJS logo"/>
                        <img class="w-7" src="../assets/images/capacitor.webp" alt="Capacitor logo"/>
                        <img class="w-7" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                        <img class="w-7" src="../assets/images/tailwind.webp" alt="TailwindCSS logo"/>
                        <img class="w-7" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                    </figure>
                </template>
                <template v-slot:content>
                    <p>
                        Digital loyalty system where the user obtains random rewards after doing a purchase.
                    </p>
                    <p>
                        With a team of friends, developed a
                        <a href="https://reachloyalty.app/" target="_blank" class="text-indigo-400 font-semibold cursor-pointer hover:text-indigo-300 duration-150">landing website</a>
                        , a
                        <a href="https://reachloyalty.app/app/login" target="_blank" class="text-indigo-400 font-semibold cursor-pointer hover:text-indigo-300 duration-150">web-app</a>
                        and an admin portal.
                    </p>
                    <p>
                        Additionally, developed the back-end for the whole infrastructure.
                    </p>
                    <p>
                        I participated in this project to further my knowledge in system architecture and full-stack
                        development.
                    </p>
                </template>
            </CustomArticle>
            <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                <img class="rounded-sm" src="../assets/images/reachloyalty-website.png"
                     alt="ReachLoyalty Website Snippet"/>
            </figure>
            <CustomArticle is-link destination="https://github.com/space-concordia-spacecraft/kronos" class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                <template v-slot:company>
                    Space Concordia
                </template>
                <template v-slot:header>
                    Kronos
                </template>
                <template v-slot:images>
                    <figure class="flex gap-3 flex-wrap">
                        <img class="w-7" src="../assets/images/cpp.png" alt="C++ logo"/>
                        <img class="h-7" src="../assets/images/freertos.png" alt="FreeRTOS logo"/>
                    </figure>
                </template>
                <template v-slot:content>
                    <p>Modular CubeSat framework based on components and busses. I took inspiration from <a target="_blank" href="https://github.com/nasa/fprime"
                        class="text-indigo-400 font-semibold cursor-pointer hover:text-indigo-300 duration-150">FPrime</a>
                        which is a framework NASA
                        created for Space projects.</p>
                    <p>Since porting FPrime to FreeRTOS and ASF proved to be nearly impossible, as the lead of the
                        Software team <a target="_blank" href="https://www.spaceconcordia.ca/en/"
                            class="text-indigo-400 font-semibold cursor-pointer hover:text-indigo-300 duration-150">@SpaceConcordia</a>,
                        I decided to create our own much simpler version of their project.</p>
                    <p>In 2023, Kronos will be launched aboard SC-ODIN, SpaceConcordia's CubeSat. </p>
                </template>
            </CustomArticle>
            <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                <img class="rounded-sm" src="../assets/images/kronos-ide.png" alt="Kronos IDE Snippet"/>
            </figure>
            <CustomArticle is-link destination="https://github.com/Ruben1729/abacus-lang" class="lg:justify-self-center lg:w-[70vw] xl:justify-self-end xl:w-[30vw]">
                <template v-slot:company>
                    Personal
                </template>
                <template v-slot:header>
                    AbacusLang
                </template>
                <template v-slot:images>
                    <figure class="flex gap-3 flex-wrap">
                        <img class="w-7" src="../assets/images/python.svg" alt="Python logo"/>
                    </figure>
                </template>
                <template v-slot:content>
                    <p>Basic stack-based programming language. I built this project to learn more about parsers, lexers,
                        and the lower level logic that governs programming languages.</p>
                </template>
            </CustomArticle>
            <figure class="lg:justify-self-center lg:w-[70vw] xl:max-w-[35vw]">
                <img class="rounded-sm" src="../assets/images/rlpindustries-website.png"
                     alt="RLP Industries Website Snippet"/>
            </figure>
        </div>
    </section>
    <section ref="about_me" id="ABOUT ME" class="relative px-5 lg:px-0">
        <CanvasColumns class="absolute"/>
        <article class="relative" id="about-me-article">
            <CustomHeading class="text-center">
                <span class="text-indigo-400">03.</span> ABOUT ME
            </CustomHeading>

            <article class="flex flex-col mb-16 lg:justify-self-center drop-shadow-2xl">
                <h6 class="text-base flex items-center border-b-[1px] border-gray-700 bg-slate-800 col-span-2 w-[100%] text-gray-400">
                    <span class="py-2 px-5 border-b-[1px] border-transparent">
                        Terminal
                    </span>
                    <span class="border-b-[1px] border-gray-600 py-2 px-5 flex items-center">
                        Local
                        <mdicon class="ml-2" size="15" name="close"/>
                    </span>
                    <mdicon class="ml-2" size="20" name="plus"/>
                    <mdicon class="ml-2" size="25" name="chevron-down"/>
                    <span class="flex-grow"></span>
                    <mdicon class="px-5 justify-self-end" size="25" name="dots-vertical"/>
                </h6>
                <article class="bg-slate-900 grid grid-cols-1-1fr gap-3 lg:w-[70vw] items-start p-5 font-mono">
                    <span class="text-indigo-400 py-1"> $ </span>
                    <p>
                        py about_me.py
                    </p>
                    <span class="py-1"> > </span>
                    <p>
                        Hey there!
                    </p>
                    <span></span>
                    <p>
                        I hope you've enjoyed browsing my website so far.
                    </p>
                    <span></span>
                    <p>
                        I'm currently a third-year Mechanical
                        Engineering
                        student at Concordia and a Computer Science DEC graduate. Even though I'm currently studying
                        Mechanical Engineering, I've found my
                        <span class="text-indigo-300">passion in web development and embedded systems</span>
                        and it's what I do for the majority of my free time.
                    </p>
                    <span></span>
                    <p>
                        In the future, I'd love to delve deeper into the web development industry and continue to
                        improve my skills in this
                        domain.
                    </p>
                    <span></span>
                    <p>
                        Here's a summary of <span class="text-indigo-300">all the technologies I've used</span> for both
                        my personal projects and professional work:
                    </p>
                    <span></span>
                    <figure class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-5">
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/html.svg" alt="HTML logo"/>
                            <figcaption>HTML</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/css.svg" alt="CSS logo"/>
                            <figcaption>CSS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/sass.svg" alt="SASS logo"/>
                            <figcaption>SASS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/javascript.svg" alt="Javascript logo"/>
                            <figcaption>Javascript</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/vuejs.webp" alt="VueJS logo"/>
                            <figcaption>VueJS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/nuxtjs.webp" alt="NuxtJS logo"/>
                            <figcaption>NuxtJS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/nestjs.svg" alt="NestJS logo"/>
                            <figcaption>NestJS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/capacitor.webp" alt="Capacitor logo"/>
                            <figcaption>Capacitor</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/mysql.webp" alt="MySQL logo"/>
                            <figcaption>MySQL</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/tailwind.webp" alt="TailwindCSS logo"/>
                            <figcaption>TailwindCSS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/nodejs.webp" alt="NodeJS logo"/>
                            <figcaption>NodeJS</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/cpp.png" alt="C++ logo"/>
                            <figcaption>C++</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/python.svg" alt="Python logo"/>
                            <figcaption>Python</figcaption>
                        </figure>
                        <figure class="flex items-center gap-2">
                            <img class="w-10" src="../assets/images/freertos.png" alt="FreeRTOS logo"/>
                            <figcaption>FreeRTOS</figcaption>
                        </figure>
                    </figure>
                    <div class="py-2"></div><div></div>
                    <span class="py-1"> > </span>
                    <p>Completed in <span class="text-indigo-300">{{Math.floor(Math.random() * 30)}}ms</span>.</p>
                    <span class="text-indigo-400 py-1"> $ </span>
                    <span class="bg-indigo-400 w-1 h-[50%] self-center"></span>
                </article>

            </article>

        </article>
    </section>
    <CustomFooter/>
</template>

<script setup>
import CustomHeading from "../components/c-h2.vue"
import CustomArticle from "../components/c-article.vue"
import CustomJobDescription from "../components/c-job-description.vue"
import CustomButton from "../components/inputs/c-button.vue"
import MatrixRain from "../components/matrix-rain";
import CanvasGrid from "../components/canvas-grid";
import CustomNavigation from "../components/c-nav.vue";
import CustomFooter from "../components/c-footer.vue";
import CanvasColumns from "../components/canvas-columns";

import { ref, onMounted, onUnmounted } from 'vue';

const home = ref();
const experience = ref();
const projects = ref();
const about_me = ref();

let homeHeight, experienceHeight, projectsHeight;

const currentSection = ref(0);
const isScrollUpVisible = ref(false);

const updateNavigation = function (_) {
    if(window.scrollY <= homeHeight) {
        currentSection.value = 0;
        isScrollUpVisible.value = false;
    } else if (window.scrollY <= experienceHeight) {
        currentSection.value = 1;
        isScrollUpVisible.value = true;
    } else if (window.scrollY <= projectsHeight) {
        currentSection.value = 2;
        isScrollUpVisible.value = true;
    } else {
        currentSection.value = 3;
        isScrollUpVisible.value = true;
    }
}

onMounted(() => {
    document.addEventListener('scroll', updateNavigation, true);

    homeHeight =        home.value.offsetHeight * 0.4;
    experienceHeight =  home.value.offsetHeight + (experience.value.offsetHeight * 0.75);
    projectsHeight =    home.value.offsetHeight + experience.value.offsetHeight + (projects.value.offsetHeight * 0.8);
})

onUnmounted(() => {
    document.removeEventListener('scroll', updateNavigation, true);
})

</script>

<style lang="scss" scoped>
ul {
    list-style-type: disc;
}

p {
    padding: 0.2rem 0;
}

.drop-anim {
    animation-name: drop-in;
    animation-duration: 3s;
}

@keyframes drop-in {
    0% {
        opacity: 0%;
        transform: translate(0, -250px);
    }
    25% {
        transform: translate(0, 0);
    }
    100% {
        opacity: 100%;
    }
}

.grid-cols-1-1fr {
    grid-template-columns: auto 1fr;
}
</style>